# init python:
#     def update_event_screens():
#         global GLOBAL_EVENT_SCREENS
#         for screen in ALL_EVENT_SCREENS:
#             if screen not in GLOBAL_EVENT_SCREENS:
#                 GLOBAL_EVENT_SCREENS.append(screen)



# default GLOBAL_EVENT_SCREENS = [
#     'MomMorningScreen14',
#     'MomMorningScreen34',
#     'MomMorningScreen24',
#     'MomMorningScreen44',
#     'MomEveningScreen24',
#     'MomEveningScreen34',
#     'MomEveningScreen44',
#     'MomNightScreen24',
#     'MomNightScreen34',
#     'MomNightScreen44',
#     'LilSisMorningScreen14',
#     'LilSisMorningScreen34',
#     'LilSisMorningScreen24',
#     'LilSisNoonScreen14',
#     'LilSisNoonScreen24',
#     'LilSisEveningScreen14',
#     'LilSisNightScreen34',
#     'LilSisEveningScreen24',
#     'LilSisEveningScreen34',
#     'LilSisEveningScreen44',
#     'LilSisAfterNoonScreen44',
#     'LilSisNightScreen44',
#     'LilSisMidnightScreen14',
#     'BigSisMorningScreen14',
#     'BigSisMorningScreen24',
#     'BigSisMorningScreen34',
#     'BigSisNoonScreen14',
#     'BigSisEveningScreen14',
#     'BigSisEveningScreen24',
#     'BigSisEveningScreen34',
#     'BigSisEveningScreen44',
#     'BigSisNightScreen34',
#     'BigSisNightScreen44',
#     'BigSisMidnightScreen14',
#     'DinnerGroupScreen',
#     'LeaveHomeScreen',
#     'LunchGroupScreen',
#     'MovieNightScreen',
#     'SchoolEntranceScreen',
#     'SchoolScreen',
#     'ToiletsFrontScreen',
#     'MansToiletScreen',
#     'WomansToiletScreen',
#     'UpTheStairsScreen',
#     'TeacherHallScreen',
#     'ArtClassFrontScreen',
#     'MedicRoomFrontScreen',
#     'SchoolGymFrontScreen',
#     'InsideSchoolGymScreen',
#     'BackYardScreen',
#     'SchoolPoolScreen',
#     'TeachersBathroomScreen',
#     'PrincipalOfficeScreen',
#     'TeachersLoungeScreen',
#     'MainClassroomScreen',
#     'NurseRoomScreen',
#     'ArtClassScreen',
#     'SchoolLibraryScreen',
#     'MannersClassScreen',
#     'BioClassScreen',
# ]

init python:
    ALL_EVENT_SCREENS = [
        'MomMorningScreen14',
        'MomMorningScreen34',
        'MomMorningScreen24',
        'MomMorningScreen44',
        'MomEveningScreen24',
        'MomEveningScreen34',
        'MomEveningScreen44',
        'MomNightScreen24',
        'MomNightScreen34',
        'MomNightScreen44',
        'LilSisMorningScreen14',
        'LilSisMorningScreen34',
        'LilSisMorningScreen24',
        'LilSisNoonScreen14',
        'LilSisNoonScreen24',
        'LilSisEveningScreen14',
        'LilSisNightScreen34',
        'LilSisEveningScreen24',
        'LilSisEveningScreen34',
        'LilSisEveningScreen44',
        'LilSisAfterNoonScreen44',
        'LilSisNightScreen44',
        'LilSisMidnightScreen14',
        'BigSisMorningScreen14',
        'BigSisMorningScreen24',
        'BigSisMorningScreen34',
        'BigSisNoonScreen14',
        'BigSisEveningScreen14',
        'BigSisEveningScreen24',
        'BigSisEveningScreen34',
        'BigSisEveningScreen44',
        'BigSisNightScreen34',
        'BigSisNightScreen44',
        'BigSisMidnightScreen14',
        'DinnerGroupScreen',
        'LeaveHomeScreen',
        'LunchGroupScreen',
        'MovieNightScreen',
        'SchoolEntranceScreen',
        'SchoolScreen',
        'ToiletsFrontScreen',
        'MansToiletScreen',
        'WomansToiletScreen',
        'UpTheStairsScreen',
        'TeacherHallScreen',
        'ArtClassFrontScreen',
        'MedicRoomFrontScreen',
        'SchoolGymFrontScreen',
        'InsideSchoolGymScreen',
        'BackYardScreen',
        'SchoolPoolScreen',
        'TeachersBathroomScreen',
        'PrincipalOfficeScreen',
        'TeachersLoungeScreen',
        'MainClassroomScreen',
        'NurseRoomScreen',
        'ArtClassScreen',
        'SchoolLibraryScreen',
        'MannersClassScreen',
        'BioClassScreen',
        'GymScreen',
        'GymLockerRoomFrontScreen',
        'GirlsLockerRoomScreen',
        'HousefrontScreen',
        'HouseToiletScreen',
        'LivingroomScreen',
        'BathroomScreen',
        'IsabellaRoomWeekendScreen',
        'JenniferRoomWeekendScreen',
        'ClaireRoomWeekendScreen',
    ]
