[package]
name = "city-dom-character-viewer"
version = "0.1.0"
description = "Standalone 3D character viewer prototype for City Dom"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1"
tauri = { version = "=2.10.1", features = [] }
tauri-plugin-cli = "=2.4.1"
tauri-plugin-fs = "=2.5.1"
tauri-runtime = "=2.10.1"
tauri-runtime-wry = "=2.10.1"
